name: Nick DeLena
favicon: null
layout_spectrum: 0.1627017033752054
typography_spectrum: 0.27633160282857716
title: Nick DeLena
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1800408372655511
  lightness: 0.6408697422593832
  saturation: 0.6640724374447018
  rhythmicContrast: 0.8836729454342276
purpose: []
